# Generated by Django 5.1.5 on 2025-02-20 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="attachments/")),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        default="CS499",
                        help_text="e.g: CS499",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        default="Untitled Course",
                        help_text="e.g: SR PROJ:TEAM SOFTWARE DESIGN",
                        max_length=250,
                    ),
                ),
                (
                    "textbook_title",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "textbook_author",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "textbook_isbn",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "textbook_link",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("font_name", models.CharField(default="Arial", max_length=100)),
                ("font_size", models.IntegerField(default=12)),
                ("header_text", models.TextField(blank=True, null=True)),
                ("footer_text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("TF", "True/False"),
                            ("MC", "Multiple Choice"),
                            ("MA", "Matching"),
                            ("FB", "Fill in the Blank"),
                            ("SA", "Short Answer"),
                            ("ES", "Essay"),
                            ("MS", "Multiple Selection"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        default="Question text.", help_text="Question Prompt."
                    ),
                ),
                (
                    "inbedded_graphic",
                    models.ImageField(
                        blank=True, max_length=200, null=True, upload_to=""
                    ),
                ),
                (
                    "choices_for_question",
                    models.TextField(
                        blank=True,
                        help_text="Answer options for the question.",
                        null=True,
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        blank=True, help_text="Correct Answer.", null=True
                    ),
                ),
                (
                    "correct_answer_graphic",
                    models.ImageField(
                        blank=True, null=True, upload_to="answer_graphics/"
                    ),
                ),
                (
                    "default_points",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
                (
                    "estimated_time",
                    models.IntegerField(
                        default=1, help_text="Estimated time to answer question."
                    ),
                ),
                ("references", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "required_reference_material",
                    models.TextField(blank=True, null=True),
                ),
                ("instructions_for_grading", models.TextField(blank=True, null=True)),
                ("instructor_comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="welcome.course"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Untitled Test.",
                        help_text="e.g: Quiz 1, Test 1",
                        max_length=200,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        help_text="Generated filename for this test.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as True when test is published/finalized.",
                    ),
                ),
                (
                    "cover_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Test instructions on cover page.",
                        null=True,
                    ),
                ),
                (
                    "test_number",
                    models.CharField(
                        blank=True,
                        help_text="Identifier, e.g. 'Test #1'",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attachments",
                    models.ManyToManyField(blank=True, to="welcome.attachment"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test",
                        to="welcome.course",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="welcome.template",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="welcome.question",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="welcome.test",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("webmaster", "Webmaster"),
                            ("publisher", "Publisher"),
                            ("teacher", "Teacher"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_points",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1, help_text="Order of question in the test."
                    ),
                ),
                ("randomize", models.BooleanField(default=False)),
                ("special_instructions", models.TextField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_appearances",
                        to="welcome.question",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_questions",
                        to="welcome.test",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("test", "question")},
            },
        ),
    ]
