# Generated by Django 5.1.5 on 2025-02-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(
                default="CS499", help_text="e.g: CS499", max_length=50, unique=True
            ),
        ),
    ]
