# Generated by Django 5.1.5 on 2025-03-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0005_remove_userprofile_owner_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_crn",
            field=models.IntegerField(default=0, help_text="e.g: 54352", max_length=50),
        ),
    ]
