# Generated by Django 5.1.5 on 2025-03-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0006_course_course_crn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_crn",
            field=models.IntegerField(default=0, help_text="e.g: 54352"),
        ),
    ]
