# Generated by Django 5.1.5 on 2025-03-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0007_alter_course_course_crn"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="textbook_version",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
