# Generated by Django 5.1.5 on 2025-03-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0008_course_textbook_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_semester",
            field=models.CharField(
                default="Fall 2021", help_text="e.g: Fall 2021", max_length=50
            ),
        ),
    ]
