# Generated by Django 5.1.5 on 2025-03-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0010_course_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_crn",
            field=models.CharField(
                default="0000", help_text="e.g: 54352", max_length=50
            ),
        ),
    ]
