# Generated by Django 5.1.5 on 2025-03-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0011_alter_course_course_crn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(
                default="CS499", help_text="e.g: CS499", max_length=50
            ),
        ),
    ]
