# Generated by Django 5.1.5 on 2025-03-22 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0012_alter_course_course_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='textbook_author',
        ),
        migrations.RemoveField(
            model_name='course',
            name='textbook_isbn',
        ),
        migrations.RemoveField(
            model_name='course',
            name='textbook_link',
        ),
        migrations.RemoveField(
            model_name='course',
            name='textbook_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='textbook_version',
        ),
        migrations.RemoveField(
            model_name='question',
            name='chapter_num',
        ),
        migrations.RemoveField(
            model_name='question',
            name='feedback_graphic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='feedback_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='general_feedback_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='required_reference_material',
        ),
        migrations.AddField(
            model_name='attachment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course associated with this attachment (teacher content).', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.PositiveIntegerField(default=0, help_text='Chapter number. Default is 0.'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Correct answer for types needing a single answer.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='include_formula',
            field=models.BooleanField(default=False, help_text='For fill in the blank: include a formula (default is No).'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.PositiveIntegerField(default=0, help_text='Section number. Default is 0.'),
        ),
        migrations.AddField(
            model_name='template',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course associated with this template (teacher content).', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.course'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Designates if this option is the correct answer.'),
        ),
        migrations.AlterField(
            model_name='dynamicquestionparameter',
            name='additional_params',
            field=models.JSONField(blank=True, help_text='Additional parameters for dynamic generation.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='estimated_time',
            field=models.IntegerField(default=1, help_text='Estimated time (in minutes) to answer the question.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='Question text.', help_text='Question prompt.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TF', 'True/False'), ('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('ES', 'Essay'), ('MA', 'Matching'), ('MS', 'Multiple Selection'), ('FB', 'Fill in the Blank'), ('DY', 'Dynamic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='references',
            field=models.CharField(blank=True, help_text='Reference text (optional).', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Template name.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course associated with this test (teacher content).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='welcome.course'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('version', models.CharField(blank=True, max_length=300, null=True)),
                ('isbn', models.CharField(blank=True, max_length=300, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='book',
            field=models.ForeignKey(blank=True, help_text='Book associated with this attachment (publisher content).', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.book'),
        ),
        migrations.AddField(
            model_name='course',
            name='book',
            field=models.ForeignKey(blank=True, help_text='Textbook associated with this course.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='welcome.book'),
        ),
        migrations.AddField(
            model_name='question',
            name='book',
            field=models.ForeignKey(blank=True, help_text='For publisher-created questions, associate with a book.', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.book'),
        ),
        migrations.AddField(
            model_name='template',
            name='book',
            field=models.ForeignKey(blank=True, help_text='Book associated with this template (publisher content).', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.book'),
        ),
        migrations.AddField(
            model_name='test',
            name='book',
            field=models.ForeignKey(blank=True, help_text='Book associated with this test (publisher content).', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.book'),
        ),
        migrations.CreateModel(
            name='CoverPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_page_name', models.CharField(help_text='Name of the cover page.', max_length=200)),
                ('test_number', models.CharField(help_text='Test number displayed on the cover page.', max_length=50)),
                ('test_date', models.DateField(help_text='Date of the test.')),
                ('test_filename', models.CharField(help_text='Filename displayed on the cover page.', max_length=200)),
                ('filename_present', models.BooleanField(default=False, help_text='Is the filename present on the cover page?')),
                ('student_name_location', models.CharField(choices=[('top_left', 'Top Left'), ('top_right', 'Top Right'), ('below_title', 'Below Title')], default='top_left', help_text="Location for the student's name on the cover page.", max_length=20)),
                ('grading_instructions_for_key', models.TextField(blank=True, help_text='Grading instructions for the answer key.', null=True)),
                ('book', models.ForeignKey(blank=True, help_text='Book associated with this cover page (publisher content).', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.book')),
                ('course', models.ForeignKey(blank=True, help_text='Course associated with this cover page (teacher content).', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.course')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(help_text='Option text (left side).')),
                ('match_text', models.TextField(help_text='Matching answer text (right side).')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_options', to='welcome.question')),
            ],
        ),
    ]
