# Generated by Django 5.1.5 on 2025-03-19 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0012_alter_course_course_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(blank=True, max_length=300, null=True)),
                ("version", models.CharField(blank=True, max_length=300, null=True)),
                ("isbn", models.CharField(blank=True, max_length=300, null=True)),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="course",
            name="textbook_author",
        ),
        migrations.RemoveField(
            model_name="course",
            name="textbook_isbn",
        ),
        migrations.RemoveField(
            model_name="course",
            name="textbook_link",
        ),
        migrations.RemoveField(
            model_name="course",
            name="textbook_title",
        ),
        migrations.RemoveField(
            model_name="course",
            name="textbook_version",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.course",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="book",
            field=models.ForeignKey(
                blank=True,
                help_text="Textbook associated with this course.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="welcome.book",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="book",
            field=models.ForeignKey(
                blank=True,
                help_text="For publisher-created questions, associate with a book if not attached to a course.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.book",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="book",
            field=models.ForeignKey(
                blank=True,
                help_text="Book associated with the publisher (required for publishers).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="welcome.book",
            ),
        ),
    ]
