# Generated by Django 5.1.5 on 2025-03-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0013_book_remove_course_textbook_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_page_name",
                    models.CharField(
                        help_text="Name of the cover page.", max_length=200
                    ),
                ),
                (
                    "test_number",
                    models.CharField(
                        help_text="Test number displayed on the cover page.",
                        max_length=50,
                    ),
                ),
                ("test_date", models.DateField(help_text="Date of the test.")),
                (
                    "test_filename",
                    models.CharField(
                        help_text="Filename displayed on the cover page.",
                        max_length=200,
                    ),
                ),
                (
                    "filename_present",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the filename is present on the cover page.",
                    ),
                ),
                (
                    "student_name_location",
                    models.CharField(
                        choices=[
                            ("top_left", "Top Left"),
                            ("top_right", "Top Right"),
                            ("below_title", "Below Title"),
                        ],
                        default="top_left",
                        help_text="Location for the student's name on the cover page.",
                        max_length=20,
                    ),
                ),
                (
                    "grading_instructions_for_key",
                    models.TextField(
                        blank=True,
                        help_text="Grading instructions for the answer key.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="question",
            name="chapter_num",
        ),
        migrations.RemoveField(
            model_name="question",
            name="feedback_graphic",
        ),
        migrations.RemoveField(
            model_name="question",
            name="feedback_type",
        ),
        migrations.RemoveField(
            model_name="question",
            name="general_feedback_text",
        ),
        migrations.RemoveField(
            model_name="question",
            name="required_reference_material",
        ),
        migrations.AddField(
            model_name="question",
            name="chapter",
            field=models.PositiveIntegerField(
                default=0, help_text="Chapter number. Default is 0."
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(
                blank=True,
                help_text="Correct answer for question types that require a single answer.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="include_formula",
            field=models.BooleanField(
                default=False,
                help_text="For fill in the blank questions: include a formula (default is No).",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="section",
            field=models.PositiveIntegerField(
                default=0, help_text="Section number. Default is 0."
            ),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="is_correct",
            field=models.BooleanField(
                default=False,
                help_text="Designates if this option is the correct answer.",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="estimated_time",
            field=models.IntegerField(
                default=1,
                help_text="Estimated time (in minutes) to answer the question.",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(
                default="Question text.", help_text="Question prompt.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("TF", "True/False"),
                    ("MC", "Multiple Choice"),
                    ("SA", "Short Answer"),
                    ("ES", "Essay"),
                    ("MA", "Matching"),
                    ("MS", "Multiple Selection"),
                    ("FB", "Fill in the Blank"),
                    ("DY", "Dynamic"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="references",
            field=models.CharField(
                blank=True,
                help_text="Reference text (optional).",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="name",
            field=models.CharField(
                help_text="Template name.", max_length=200, unique=True
            ),
        ),
        migrations.CreateModel(
            name="MatchingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.TextField(help_text="Option text (left side).")),
                (
                    "match_text",
                    models.TextField(help_text="Matching answer text (right side)."),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_options",
                        to="welcome.question",
                    ),
                ),
            ],
        ),
    ]
