# Generated by Django 5.1.5 on 2025-03-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0013_remove_attachment_name_remove_course_textbook_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Template name.', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course', 'name'), name='unique_name_per_course'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(condition=models.Q(('book__isnull', False)), fields=('book', 'name'), name='unique_name_per_book'),
        ),
    ]
