# Generated by Django 5.1.5 on 2025-03-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0014_alter_template_name_template_unique_name_per_course_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='template',
            name='unique_name_per_course',
        ),
        migrations.RemoveConstraint(
            model_name='template',
            name='unique_name_per_book',
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Template name.', max_length=200, unique=True),
        ),
    ]
