# Generated by Django 5.1.5 on 2025-03-19 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0014_coverpage_remove_question_chapter_num_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="name",
        ),
        migrations.AddField(
            model_name="attachment",
            name="book",
            field=models.ForeignKey(
                blank=True,
                help_text="Book associated with this attachment (publisher content).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.book",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Course associated with this attachment (teacher content).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.course",
            ),
        ),
        migrations.AddField(
            model_name="coverpage",
            name="book",
            field=models.ForeignKey(
                blank=True,
                help_text="Book associated with this cover page (publisher content).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.book",
            ),
        ),
        migrations.AddField(
            model_name="coverpage",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Course associated with this cover page (teacher content).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.course",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="book",
            field=models.ForeignKey(
                blank=True,
                help_text="Book associated with this template (publisher content).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.book",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Course associated with this template (teacher content).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.course",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="book",
            field=models.ForeignKey(
                blank=True,
                help_text="Book associated with this test (publisher content).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.book",
            ),
        ),
        migrations.AlterField(
            model_name="coverpage",
            name="filename_present",
            field=models.BooleanField(
                default=False, help_text="Is the filename present on the cover page?"
            ),
        ),
        migrations.AlterField(
            model_name="dynamicquestionparameter",
            name="additional_params",
            field=models.JSONField(
                blank=True,
                help_text="Additional parameters for dynamic generation.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="book",
            field=models.ForeignKey(
                blank=True,
                help_text="For publisher-created questions, associate with a book.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.book",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(
                blank=True,
                help_text="Correct answer for types needing a single answer.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="include_formula",
            field=models.BooleanField(
                default=False,
                help_text="For fill in the blank: include a formula (default is No).",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Course associated with this test (teacher content).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="welcome.course",
            ),
        ),
    ]
