# Generated by Django 5.1.5 on 2025-03-23 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0015_remove_template_unique_name_per_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='test',
            name='book',
        ),
        migrations.RemoveField(
            model_name='question',
            name='book',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='book',
        ),
        migrations.RemoveField(
            model_name='course',
            name='book',
        ),
        migrations.RemoveField(
            model_name='coverpage',
            name='book',
        ),
        migrations.RemoveField(
            model_name='template',
            name='book',
        ),
        migrations.RemoveField(
            model_name='matchingoption',
            name='question',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_code',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_crn',
            new_name='crn',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_semester',
            new_name='sem',
        ),
        migrations.RenameField(
            model_name='coverpage',
            old_name='test_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='coverpage',
            old_name='test_filename',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='coverpage',
            old_name='grading_instructions_for_key',
            new_name='instructions',
        ),
        migrations.RenameField(
            model_name='coverpage',
            old_name='cover_page_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='coverpage',
            old_name='filename_present',
            new_name='showFilename',
        ),
        migrations.RenameField(
            model_name='coverpage',
            old_name='test_number',
            new_name='testNum',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer_graphic',
            new_name='ansimg',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='owner',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='instructor_comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='instructions_for_grading',
            new_name='directions',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='estimated_time',
            new_name='eta',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='references',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='default_points',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='font_name',
            new_name='bodyFont',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='font_size',
            new_name='bodyFontSize',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='footer_text',
            new_name='footerText',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='header_text',
            new_name='headerText',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='coverpage',
            name='student_name_location',
        ),
        migrations.RemoveField(
            model_name='question',
            name='embedded_graphic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='include_formula',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='test',
            name='cover_instructions',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_number',
        ),
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='attachmentname', help_text='attachment name', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coverpage',
            name='blank',
            field=models.CharField(choices=[('TL', 'Top Left'), ('TR', 'Top Right'), ('BT', 'Below Title')], default='top_left', help_text="Location for the student's name on the cover page.", max_length=20),
        ),
        migrations.AddField(
            model_name='coverpage',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='graphics/'),
        ),
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('tf', 'True/False'), ('mc', 'Multiple Choice'), ('sa', 'Short Answer'), ('es', 'Essay'), ('ma', 'Matching'), ('ms', 'Multiple Selection'), ('fb', 'Fill in the Blank'), ('dy', 'Dynamic')], default='tf', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='coverPage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='pageNumbersInFooter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='pageNumbersInHeader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='subtitleFont',
            field=models.CharField(default='Arial', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='subtitleFontSize',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='template',
            name='titleFont',
            field=models.CharField(default='Arial', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='titleFontSize',
            field=models.IntegerField(default=48),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Correct answer text', null=True)),
                ('answer_graphic', models.ImageField(blank=True, null=True, upload_to='answer_graphics/')),
                ('response_feedback_text', models.TextField(blank=True, null=True)),
                ('response_feedback_graphic', models.ImageField(blank=True, null=True, upload_to='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='welcome.question')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Answer option text', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='welcome.question')),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('version', models.CharField(blank=True, max_length=300, null=True)),
                ('isbn', models.CharField(blank=True, max_length=300, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='textbook',
            field=models.ForeignKey(blank=True, help_text='Book associated with this attachment (publisher content).', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.textbook'),
        ),
        migrations.AddField(
            model_name='course',
            name='textbook',
            field=models.ForeignKey(blank=True, help_text='Textbook associated with this course.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='welcome.textbook'),
        ),
        migrations.AddField(
            model_name='coverpage',
            name='textbook',
            field=models.ForeignKey(blank=True, help_text='Book associated with this cover page (publisher content).', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.textbook'),
        ),
        migrations.AddField(
            model_name='question',
            name='textbook',
            field=models.ForeignKey(blank=True, help_text='For publisher-created questions, associate with a book.', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.textbook'),
        ),
        migrations.AddField(
            model_name='template',
            name='textbook',
            field=models.ForeignKey(blank=True, help_text='Book associated with this template (publisher content).', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.textbook'),
        ),
        migrations.AddField(
            model_name='test',
            name='textbook',
            field=models.ForeignKey(blank=True, help_text='Book associated with this test (publisher content).', null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.textbook'),
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='MatchingOption',
        ),
    ]
