# Generated by Django 5.1.5 on 2025-03-24 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0016_remove_book_publisher_remove_test_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.userprofile'),
        ),
    ]
