# Generated by Django 5.1.5 on 2025-03-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0017_alter_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'userprofile__role': 'teacher'}, related_name='courses', to='welcome.userprofile'),
        ),
    ]
