# Generated by Django 5.1.5 on 2025-03-24 02:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0019_alter_course_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'userprofile__role': 'teacher'}, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
