# Generated by Django 5.1.5 on 2025-03-24 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0020_alter_course_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField(default=1, help_text='Part number within the test')),
                ('test', models.ForeignKey(help_text='Test this part belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='welcome.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(default=1, help_text='Section number within the part')),
                ('question_type', models.CharField(help_text='Type of questions in this section', max_length=50)),
                ('part', models.ForeignKey(help_text='Part this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='welcome.testpart')),
            ],
        ),
        migrations.AddField(
            model_name='testquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.testsection'),
        ),
    ]
