# Generated by Django 5.1.5 on 2025-03-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0022_template_part_structure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='part_structure',
            new_name='partStructure',
        ),
    ]
