# Generated by Django 5.1.5 on 2025-03-29 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("welcome", "0023_rename_part_structure_template_partstructure"),
    ]

    operations = [
        migrations.AddField(
            model_name="options",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image for the option (extra support).",
                null=True,
                upload_to="option_images/",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="name",
            field=models.CharField(help_text="Attachment name", max_length=300),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="textbook",
            field=models.ForeignKey(
                blank=True,
                help_text="Textbook associated with this attachment (publisher content).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.textbook",
            ),
        ),
        migrations.AlterField(
            model_name="coverpage",
            name="blank",
            field=models.CharField(
                choices=[
                    ("TL", "Top Left"),
                    ("TR", "Top Right"),
                    ("BT", "Below Title"),
                ],
                default="TL",
                help_text="Location for the student's name on the cover page.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coverpage",
            name="showFilename",
            field=models.BooleanField(
                default=False, help_text="Display the filename on the cover page?"
            ),
        ),
        migrations.AlterField(
            model_name="coverpage",
            name="textbook",
            field=models.ForeignKey(
                blank=True,
                help_text="Textbook associated with this cover page (publisher content).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.textbook",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.TextField(
                blank=True,
                help_text="Correct answer for types requiring a single answer.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="chapter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Chapter number. Must be non-negative for publisher questions.",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="textbook",
            field=models.ForeignKey(
                blank=True,
                help_text="For publisher-created questions, associate with a textbook.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.textbook",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="textbook",
            field=models.ForeignKey(
                blank=True,
                help_text="Textbook associated with this template (publisher content).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.textbook",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="textbook",
            field=models.ForeignKey(
                blank=True,
                help_text="Textbook associated with this test (publisher content).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="welcome.textbook",
            ),
        ),
    ]
