# Generated by Django 5.1.5 on 2025-03-31 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0025_feedback_averagescore_question_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course associated with this attachment (teacher content).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_set', to='welcome.course'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='textbook',
            field=models.ForeignKey(blank=True, help_text='Textbook associated with this attachment (publisher content).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_set', to='welcome.textbook'),
        ),
    ]
