# Generated by Django 5.1.5 on 2025-04-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0026_alter_attachment_course_alter_attachment_textbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='coverPage',
            field=models.CharField(help_text='cover page settings.', max_length=1000),
        ),
    ]
