# Generated by Django 5.1.5 on 2025-04-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0027_alter_template_coverpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='coverPageData',
            field=models.CharField(default="{name: 'Default 1st Test',testNum: 1,date: `${year}-${month}-${date}`,file: 'defaultpage',showFilename: true, blank: 'TR',instructions: 'Grade according to the rubric, giving partial credit where indicated',published: 1,}", help_text='cover page settings.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='template',
            name='coverPage',
            field=models.IntegerField(default=0),
        ),
    ]
