# Generated by Django 5.1.5 on 2025-04-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0029_attachment_author_coverpage_author_template_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Template name.', max_length=200),
        ),
    ]
