# Generated by Django 5.1.5 on 2025-04-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0030_alter_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='CS499', help_text='e.g: CS499', max_length=50, unique=True),
        ),
    ]
