# Generated by Django 5.1.5 on 2025-04-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0031_alter_course_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='pair',
            field=models.JSONField(blank=True, help_text='JSON representation of matching pairs', null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='options',
            name='pair',
            field=models.JSONField(blank=True, help_text='JSON representation of matching pairs', null=True),
        ),
    ]
