# Generated by Django 5.1.5 on 2025-04-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0033_feedback_time_alter_textbook_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='coverPage',
            new_name='coverPageID',
        ),
        migrations.RemoveField(
            model_name='template',
            name='coverPageData',
        ),
    ]
