# Generated by Django 5.1.5 on 2025-04-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0034_rename_coverpage_template_coverpageid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='courseTag',
            field=models.CharField(blank=True, help_text='Template course tag.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='dateTag',
            field=models.CharField(blank=True, help_text='Template date tag.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='nameTag',
            field=models.CharField(blank=True, help_text='Template name tag.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(blank=True, help_text='Template name.', max_length=200, null=True),
        ),
    ]
