# Generated by Django 5.1.5 on 2025-04-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0035_template_coursetag_template_datetag_template_nametag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='templateIndex',
            new_name='templateID',
        ),
        migrations.AddField(
            model_name='template',
            name='bonusQuestions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
