# Generated by Django 5.1.5 on 2025-04-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0036_rename_templateindex_test_templateid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testquestion',
            unique_together={('test', 'question', 'section')},
        ),
    ]
