# Generated by Django 5.1.5 on 2025-04-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0037_alter_testquestion_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='textbook',
        ),
        migrations.AddField(
            model_name='course',
            name='textbook',
            field=models.ManyToManyField(blank=True, help_text='Textbook associated with this course.', null=True, to='welcome.textbook'),
        ),
    ]
