# Generated by Django 5.1.5 on 2025-04-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0038_remove_course_textbook_course_textbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='textbook',
        ),
        migrations.AddField(
            model_name='course',
            name='textbooks',
            field=models.ManyToManyField(blank=True, help_text='Textbook associated with this course.', to='welcome.textbook'),
        ),
    ]
