# Generated by Django 5.1.5 on 2025-04-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0039_remove_course_textbook_course_textbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='requiredRefs',
            field=models.CharField(blank=True, help_text='Required Reference text.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='questions', to='welcome.test'),
        ),
        migrations.AddField(
            model_name='test',
            name='refText',
            field=models.CharField(blank=True, help_text='Reference text (optional).', max_length=200, null=True),
        ),
    ]
