# Generated by Django 5.1.5 on 2025-04-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0040_question_requiredrefs_question_tests_test_reftext'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ansimgID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='imgID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
